development:
  sessions:
    default:
      database: tothcms_development
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true

test:
  sessions:
    default:
      database: tothcms_test
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true

production:
  sessions:
    default:
      # heroku
      uri: <%= ENV['MONGOHQ_URL'] %>
      # database: tothcms_production
      # hosts:
      #   - localhost:27017
  options:
    identity_map_enabled: true
